services:
  server:
    container_name: server
    build: ./server/.devcontainer
    volumes:
      - ./server:/app
    user: vscode
    working_dir: /app
    command: sleep infinity
    networks:
      - network
    environment:
      - MEMORY_FILE=./memory.md
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=frl
      - MONGODB_URI=mongodb://mongo:27017
      - MONGO_DB=frl
      - MONGO_DB_USERNAME=frl
      - MONGO_DB_PASSWORD=frl_123
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_OCR_MODEL=MedAIBase/PaddleOCR-VL:0.9b
      - OLLAMA_MODEL=llama3.2:3b
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: frl
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  mongo:
    container_name: mongo
    image: mongo:8.2.3-noble
    restart: unless-stopped
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_123
      - MONGO_DB=frl
      - MONGO_DB_USERNAME=frl
      - MONGO_DB_PASSWORD=frl_123
    volumes:
      - mongo-data:/var/lib/mongo/data
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    networks:
      - network
  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - network
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 1s
      timeout: 1s
      retries: 3600
    runtime: nvidia
volumes:
  minio_data:
  mongo-data:
  ollama_data:
networks:
  network:
    driver: bridge
